version: "2.4"

networks:
  web:
    external: true
  grocy:
    internal: true
    driver: bridge

services:
  nginx:
    image: "grocy/nginx:${GROCY_IMAGE_TAG:-latest}"
    labels:
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:grocy.aemo.dev
      - traefik.docker.network=web
      - traefik.port=8080
    build:
      args:
        GROCY_VERSION: v3.0.1
      context: .
      dockerfile: Dockerfile-grocy-nginx
    depends_on:
      - grocy
    networks:
      - web
      - grocy
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/nginx
    container_name: nginx
  grocy:
    image: "grocy/grocy:${GROCY_IMAGE_TAG:-latest}"
    build:
      args:
        GROCY_VERSION: v3.0.1
      context: .
      dockerfile: Dockerfile-grocy
    networks:
      - grocy
    expose:
      - "9000"
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /var/log/php7
      - app-db:/var/www/data
    env_file:
      - grocy.env
    container_name: grocy

volumes:
  app-db:
